### ISSUE TITLE
Task: Explore Using `Nextra` for Docs Site with Search + Auth

### ISSUE THREAD

**Issue by nelsonic** [dwyl/nextra-demo#1]
We need to build a Documentation Website that has:
1. Fast page load times - e.g. via server-side rendering or _static_ pages. 
2. Authentication - so we can protect certain pages. 
3. Full-text Search - so people can _find_ what they are looking for when there are _many_ pages.

We are going to use the `nextra` https://nextra.site framework for building this site.

# Todo

+ [x] Create a new project/repo: https://github.com/dwyl/nextra-demo (will be `public` soon ...) 
+ [x] Create a brand new `nextra` project in it. 
+ [x] Document _all_ the steps you take for creating the project; no step is too small. 
+ [x] Add authentication: OAuth2 via: https://nextjs.org/docs/app/building-your-application/authentication 
(if you get stuck, comment on this issue for help!)
+ [x] Add some basic content to the site 3-5 pages is enough. Can be about _any_ topic you like; Kittens, Boats, Chocolate, BTC, doesn't matter. 
+ [x] Protect 2 of the pages using `auth` i.e. should `404` if the person is not authenticated but display if they are. 
  + [x] Document how this is done.
+ [ ] Enable search. 
  + [ ] Search should only surface the `public` pages if the person is not authenticated.
  + [ ] Should show the `private` pages if the person has logged in. 
+ [x] Tests! 🧪 we need decent (preferably 100%) test coverage on this demo. 💯 
+ [x] Analytics 📈 📊 https://github.com/dwyl/learn-analytics/issues/3
