### ISSUE TITLE
Add https://analytics.dwyl.com to Nextra Demo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/nextra-demo#13]
# Todo

+ [x] Deploy the Nextra Demo _preferably_ as `GitHub` Pages :octocat: 
  + [x] but if the `auth` requires a `Vercel` deployment, fork the repo and do it on your own account (_document the steps_) 🙏 
+ [x] create an `analytics.md` file in the root of this repo. 🆕 
+ [x] Give a basic intro and explain how to use `Plausible Analytics` in a `Nextra`/`Next.js` site 📝 
+ [x] Link directly to where you have documented this in: https://github.com/dwyl/learn-analytics/tree/main/plausible#3-optional-monitoring-a-nextjs-website 🔗 
+ [x] Confirm that it's working by sharing a screenshot of the `Analytics` dashboard.
